/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_Librarian;

import Author.Author;
import Book.Book;
import Genre.Genre;
import Library.Business;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaoyifan
 */
public class BookJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookJPanel
     */
    
     Business business;
    DefaultTableModel tableModel;
    public BookJPanel(Business business) {
        initComponents();
        this.business = business;
         this.tableModel = (DefaultTableModel) jTable1.getModel();
         populate();
         populateDropDowns();
    }
    public BookJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FieldName = new javax.swing.JTextField();
        FieldAbstract = new javax.swing.JTextField();
        FieldPrice = new javax.swing.JTextField();
        FieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GenreBtn = new javax.swing.JButton();
        AuthorBtn = new javax.swing.JButton();
        AuthorBox = new javax.swing.JComboBox();
        GenreBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book Title", "Book ID", "abstract", "price", "Genre", "Author"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 252, 1029, 221));

        FieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNameActionPerformed(evt);
            }
        });
        add(FieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 35, 177, 31));

        FieldAbstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldAbstractActionPerformed(evt);
            }
        });
        add(FieldAbstract, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 19, 406, 119));

        FieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPriceActionPerformed(evt);
            }
        });
        add(FieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 191, 177, 31));

        FieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDActionPerformed(evt);
            }
        });
        add(FieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 120, 177, 31));

        jLabel1.setText("Title");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 42, -1, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 127, -1, -1));

        jLabel3.setText("abstract");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 62, -1, -1));

        jLabel4.setText("price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 198, -1, -1));

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 88, -1, -1));

        ViewBtn.setText("view");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        add(ViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 491, -1, -1));

        jLabel5.setText("Genre");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel6.setText("Author");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        GenreBtn.setText("Assign Genre");
        GenreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreBtnActionPerformed(evt);
            }
        });
        add(GenreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        AuthorBtn.setText("Assign Author");
        AuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorBtnActionPerformed(evt);
            }
        });
        add(AuthorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, -1, -1));

        add(AuthorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 186, -1));

        add(GenreBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 166, 186, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNameActionPerformed

    private void FieldAbstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldAbstractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldAbstractActionPerformed

    private void FieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPriceActionPerformed

    private void FieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIDActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        
        this.business.getBookDirectory().createBook(FieldName.getText(), FieldID.getText(), FieldAbstract.getText(), Double.parseDouble(FieldPrice.getText()));
        populate();
    }//GEN-LAST:event_AddBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void GenreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreBtnActionPerformed
        // TODO add your handling code here:
            this.business.getBookDirectory().findByID(FieldID.getText()).setGenre((Genre)GenreBox.getSelectedItem());
            populate();
    }//GEN-LAST:event_GenreBtnActionPerformed

    private void AuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorBtnActionPerformed
        // TODO add your handling code here:
            this.business.getBookDirectory().findByID(FieldID.getText()).setAuthor((Author)AuthorBox.getSelectedItem());
            populate();
    }//GEN-LAST:event_AuthorBtnActionPerformed


    public void populate(){
    tableModel.setRowCount(0);
        for (Book g : this.business.getBookDirectory().getBooks()) {
            
            Object[] row = new Object[6];
            
            row[0] = g.getName();
            row[1] = g.getId();
            row[2] = g.getAbstraction();
            row[3] = g.getPrice();
            row[4] = g.getGenre();
            row[5] = g.getAuthor();
    
            tableModel.addRow(row);
        }
    }
    
    public void populateDropDowns(){
    
    List<Genre> genreList = this.business.getGenreDirecotry().getGenres();
    
    List<Author> authorList = this.business.getAuthorDirectory().getAuthors();
    
    
    for(Author a : authorList){
        AuthorBox.addItem(a);
    }
    
    for(Genre g : genreList){
        GenreBox.addItem(g);
    }
   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JComboBox AuthorBox;
    private javax.swing.JButton AuthorBtn;
    private javax.swing.JTextField FieldAbstract;
    private javax.swing.JTextField FieldID;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldPrice;
    private javax.swing.JComboBox GenreBox;
    private javax.swing.JButton GenreBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
