/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ShanSun
 */
public class CatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CatalogPannel
     */
    Application application;
    
    Medicine medicine;
    
    DefaultTableModel medTableModel;
    public CatalogJPanel() {
        initComponents();
    }

    public CatalogJPanel(Application application) {
         initComponents();
        this.application = application;
        this.medTableModel = (DefaultTableModel) MedicineCatalog.getModel();
        displayMedicineCatalog();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineCatalog = new javax.swing.JTable();
        DosageField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedicineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Name", "Dosage"
            }
        ));
        jScrollPane1.setViewportView(MedicineCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 58, -1, -1));
        add(DosageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 249, 124, 50));

        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 127, 124, 51));

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 531, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String dosage = DosageField.getText();
        
        MedicineCatalog catalog = this.application.getCatalog();
        
        catalog.createMedicine(name, Double.valueOf(dosage));
    }//GEN-LAST:event_AddBtnActionPerformed

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
        
        String name = nameField.getText();
        
        Boolean isUnique = this.application.getCatalog().checkIfMedicineUnique(name);
        
        if(isUnique){
            
        }else{
            nameField.setText("");
        JOptionPane.showMessageDialog(null, "medicine already existed");
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = MedicineCatalog.getSelectedRow();
        
         if(selectedRow >=0){
             this.medicine = (Medicine)medTableModel.getValueAt(selectedRow, 0);
            
            this.application.getCatalog().removeMedicine(this.medicine.getMedicineName());
            
        }else{
        
            JOptionPane.showMessageDialog(null, "Please select a row!");
                    
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    
    public void displayMedicineCatalog(){
    
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicinList();
        
        if(medicines.size() >0){
        
        medTableModel.setRowCount(0);
        
            for(Medicine med : medicines){

                Object row[] = new Object[2];

                row[0] = med;
                row[1] = med.getDosage();
                medTableModel.addRow(row);
            }
        
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DosageField;
    private javax.swing.JTable MedicineCatalog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
