/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Application;

/**
 *
 * @author shaoyifan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Application application;
    
  
    public MainFrame() {
        initComponents();
        
        this.application = new Application();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        CreateObservationBtn = new javax.swing.JButton();
        VitalSignHistoryBtn = new javax.swing.JButton();
        assignMedicineBtn = new javax.swing.JButton();
        medicineCatlogBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateObservationBtn.setText("CreateObservation");
        CreateObservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateObservationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CreateObservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        VitalSignHistoryBtn.setText("View Vital sign History");
        VitalSignHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalSignHistoryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(VitalSignHistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        assignMedicineBtn.setText("Assign Medicine");
        assignMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedicineBtnActionPerformed(evt);
            }
        });
        jPanel1.add(assignMedicineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        medicineCatlogBtn.setText("Medicine Catalog");
        medicineCatlogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineCatlogBtnActionPerformed(evt);
            }
        });
        jPanel1.add(medicineCatlogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VitalSignHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalSignHistoryBtnActionPerformed
        // TODO add your handling code here:
         jSplitPane1.setRightComponent(new ViewJPanel(this.application));
    }//GEN-LAST:event_VitalSignHistoryBtnActionPerformed

    private void assignMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedicineBtnActionPerformed
        // TODO add your handling code here:
          jSplitPane1.setRightComponent(new MedicineAssignPanel(this.application));
    }//GEN-LAST:event_assignMedicineBtnActionPerformed

    private void CreateObservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateObservationBtnActionPerformed
        // TODO add your handling code here:
        
        jSplitPane1.setRightComponent(new CreateJpanel(this.application));
    }//GEN-LAST:event_CreateObservationBtnActionPerformed

    private void medicineCatlogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineCatlogBtnActionPerformed
        // TODO add your handling code here:
         jSplitPane1.setRightComponent(new CatalogJPanel(this.application));
    }//GEN-LAST:event_medicineCatlogBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateObservationBtn;
    private javax.swing.JButton VitalSignHistoryBtn;
    private javax.swing.JButton assignMedicineBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medicineCatlogBtn;
    // End of variables declaration//GEN-END:variables
}
