/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author shaoyifan
 */
public class MedicineAssignPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAssignPanel
     */
     Application application;
    public MedicineAssignPanel() {
        initComponents();
    }
    
     public MedicineAssignPanel(Application application) {
        initComponents();
        
        this.application = application;
        
        populateDropDowns();
    }
     
     public void populateDropDowns(){
    
    ArrayList<Medicine> medicines = this.application.getCatalog().getMedicinList();
    
    ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
    
    
    for(Observation o : observations){
            ObservationBox.addItem(o);
    }
    
    for(Medicine med : medicines){
    
        MedicineBox.addItem(med);
   
    }
    
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObservationBox = new javax.swing.JComboBox();
        MedicineBox = new javax.swing.JComboBox();
        AssignBtn = new javax.swing.JButton();

        ObservationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservationBoxActionPerformed(evt);
            }
        });

        AssignBtn.setText("AssignMed");
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ObservationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(MedicineBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(AssignBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObservationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicineBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(AssignBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        // TODO add your handling code here:

        Observation o = (Observation)ObservationBox.getSelectedItem();
        Medicine m = (Medicine)MedicineBox.getSelectedItem();
        o.setMedicine(m);
    }//GEN-LAST:event_AssignBtnActionPerformed

    private void ObservationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservationBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JComboBox MedicineBox;
    private javax.swing.JComboBox ObservationBox;
    // End of variables declaration//GEN-END:variables
}
